---
  - name: install mysql and python-myslqdb
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
      - python3-mysqldb
      - mariadb-server
    register: result_out
